version: '3.8'

services:
  mariadb:
    image: mariadb:11
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_USER=${USER}
      - MARIADB_PASSWORD=${PWD}
      - MARIADB_DATABASE=${DATABASE}
      - MARIADB_ROOT_PASSWORD=${ROOTPWD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - bloobin-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloobin
    ports:
      - 5000:5000
    environment:
      APP_ENV: "dev"
      APP_PORT: 5000
      DB: ${DATABASE}
      DB_USER: ${USER}
      DB_PWD: ${PWD}
      MARIA_HOST: ${MARIA_HOST}
    depends_on:
      - mariadb
      # - mongo
    networks:
      - bloobin-network

  # mongo:
  #   image: mongo:6.0.6
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: ${ROOTPWD}
  #   networks:
  #     - bloobin-network

networks:
  bloobin-network:
